import os
import random
from datetime import datetime

import numpy as np
import torch


class Config:
    # ==========================================
    # 1. Path configurations
    # ==========================================
    # HPC default: keep experiments under the project checkout, while allowing
    # local runs to override the dataset mount with RP_DATASET_ROOT.
    BASE_DIR = r"/raid/candi/jiayi/RP"
    DATASET_ROOT = os.environ.get("RP_DATASET_ROOT", os.path.join(BASE_DIR, "data"))
    UNIFIED_DATA_DIR = os.path.join(DATASET_ROOT, "Unified_Dataset")
    SPLIT_DIR = os.path.join(UNIFIED_DATA_DIR, "splits")
    EXP_DIR = os.path.join(BASE_DIR, "Experiments")

    # ==========================================
    # 2. Experiment mode
    # ==========================================
    # Options:
    #   "B1_TCIA_TBX_BASELINE"
    #       Main baseline: TCIA TBx-confirmed radiologist target lesion ROIs only.
    #
    #   "B2_TCIA_SBX_ONLY"
    #       TCIA systematic-biopsy region supervision only.
    #
    #   "B3_TCIA_TBX_SBX"
    #       TCIA TBx-confirmed target ROIs + TCIA SBx region supervision.
    #
    #   Legacy/reference modes are kept below for comparison with older runs:
    #       N1_RADIOLOGIST_ONLY, N2_PUB_TCIA_TBX_ONLY,
    #       N3_PUB_TCIA_SBX_ONLY, N4_MIXED.
    #
    # B1 and all N1-N4 experiments use the same unmasked PUB + TCIA internal
    # evaluation cohort. This allows these experiments to report:
    #   - lesion Dice on valid PUB dense-mask cases;
    #   - patient-level risk-map metrics from available segmentation masks;
    #   - region-level risk-map metrics from available masks and zone maps.
    #
    # Change only this value to switch experiments.
    EXPERIMENT_MODE = "B1_TCIA_TBX_BASELINE"

    # Shared internal evaluation cohort generated by
    # preprocessing/Dataset_split_generator.py.
    COMMON_INTERNAL_VAL_CSV = os.path.join(
        SPLIT_DIR, "common_internal_evaluation.csv"
    )

    # Use the same checkpoint-selection rule for fair N1-N4 comparison.
    # The evaluate/train code must calculate "composite" from the valid
    # lesion-, patient-, and region-level metrics using their label masks.
    COMMON_BEST_MODEL_METRIC = "composite"

    if EXPERIMENT_MODE == "B1_TCIA_TBX_BASELINE":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B1_TCIA_TBx_baseline_train.csv"
        )
        # Use the shared PUB + TCIA internal cohort for validation so B1 can
        # report PUB lesion Dice while still reporting biopsy-based TCIA
        # patient/region metrics through label availability masks.
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "B1_PROMIS_external_val.csv"
        )

        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "tbx_roi_auprc"
        EXPERIMENT_TAG = "B1_TCIA_TBxROI_PosNeg_OutsideGland"

    elif EXPERIMENT_MODE == "B2_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B2_TCIA_SBx_only_train.csv"
        )
        VAL_CSV = os.path.join(
            SPLIT_DIR, "B2_TCIA_SBx_only_internal_val.csv"
        )
        TEST_CSV = os.path.join(
            SPLIT_DIR, "B2_PROMIS_external_val.csv"
        )

        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "clinical_bacc"
        EXPERIMENT_TAG = "B2_TCIA_SBxOnly"

    elif EXPERIMENT_MODE == "B3_TCIA_TBX_SBX":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B3_TCIA_TBx_SBx_train.csv"
        )
        VAL_CSV = os.path.join(
            SPLIT_DIR, "B3_TCIA_TBx_SBx_internal_val.csv"
        )
        TEST_CSV = os.path.join(
            SPLIT_DIR, "B3_PROMIS_external_val.csv"
        )

        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 10

        BEST_MODEL_METRIC = "clinical_bacc"
        EXPERIMENT_TAG = "B3_TCIA_TBxROI_SBx_PosNeg"

    elif EXPERIMENT_MODE == "N1_RADIOLOGIST_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N1_radiologist_only_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N1_PROMIS_external_val.csv"
        )

        # Train strictly on PUB cases with dense radiologist lesion masks.
        # Keep common validation unfiltered across supervised PUB/TCIA cases
        # so the run can still report comparison metrics.
        TASK = "mixed"
        DATASET_TASK = "mixed"
        TRAIN_DATASET_TASK = "radiologist_only"
        VAL_DATASET_TASK = "mixed"
        TEST_DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "lesion_dice"
        EXPERIMENT_TAG = "N1_PUBDenseOnly_CommonEval"

    elif EXPERIMENT_MODE == "N2_PUB_TCIA_TBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N2_PUB_TCIA_TBx_only_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N2_PROMIS_external_val.csv"
        )

        # The N2 training CSV contains PUB + TCIA TBx supervision.
        # TCIA SBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.05
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = True
        USE_CURRICULUM = True

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 10
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N2_PUB_TCIA_TBxOnly_CommonEval"

    elif EXPERIMENT_MODE == "N3_PUB_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N3_PUB_TCIA_SBx_only_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N3_PROMIS_external_val.csv"
        )

        # The N3 training CSV contains PUB + TCIA SBx supervision.
        # TCIA TBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 0.25

        USE_EM_WEIGHTING = True
        USE_CURRICULUM = True

        # Epoch 1-9: PUB dense only
        # Epoch 10+:  PUB dense + TCIA SBx
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 10

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N3_PUB_TCIA_SBxOnly_CommonEval"

    elif EXPERIMENT_MODE == "N4_MIXED":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N4_mixed_PUB_TCIA_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N4_mixed_PROMIS_external_val.csv"
        )

        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.05
        LESION_SYS_LOSS_WEIGHT = 0.25

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        # Evidence-guided N4 default after N2/N3 sweeps:
        # Epoch 1-14:  PUB dense only
        # Epoch 15+:   PUB dense + TCIA TBx + TCIA SBx
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 15
        LESION_SYS_START_EPOCH = 15

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N4_FixedW005_025_Curr15_15_CommonEval"

    else:
        raise ValueError(
            "Unsupported EXPERIMENT_MODE: "
            f"{EXPERIMENT_MODE}. "
            "Use B1_TCIA_TBX_BASELINE, B2_TCIA_SBX_ONLY, "
            "B3_TCIA_TBX_SBX, or the legacy N1/N2/N3/N4 modes."
        )

    # ==========================================
    # 3. Data and preprocessing
    # ==========================================
    TARGET_SPACING = [1.0, 1.0, 2.24]
    CROP_SIZE_SITK = [64, 64, 32]
    INPUT_SHAPE = (3, 32, 64, 64)
    # TCIA TBx supervision uses radiologist target lesion ROIs labelled by
    # target-biopsy-confirmed grade, not the inserted needle track.
    TCIA_TARGET_MASK_FILENAME = "target_mask.nii.gz"
    # Used only during preprocessing to match biopsy cores to target ROIs.
    NEEDLE_RADIUS = 2

    # ==========================================
    # 4. Model and labels
    # ==========================================
    IN_CHANNELS = 3
    NUM_CLASSES = 7

    # Compatibility values for the revised segmentation/MIL model.
    BASE_CHANNELS = 32
    MAX_ZONES = 20
    MIL_POOLING = "lme"
    LME_R = 8.0
    DROPOUT_RATE = 0.2
    # Segmentation-derived patient/region metrics pool voxel risk maps into
    # case/zone scores. top_percent is less sensitive to isolated noisy voxels
    # than pure max pooling.
    SEG_PATIENT_POOLING = "top_percent"
    SEG_REGION_POOLING = "top_percent"
    SEG_RISK_TOP_PERCENT = 1.0
    SEG_RISK_LME_R = 8.0
    SEG_REGION_POSITIVE_MIN_VOXELS = 1

    # Label convention:
    # 0: negative/background, 1: benign, 2: ISUP1,
    # 3: ISUP2, ..., 6: ISUP5.
    CSPC_THRESHOLD = 3
    LESION_POSITIVE_THRESHOLD = CSPC_THRESHOLD
    INVALID_SYS_LABEL = -1
    PRED_PROB_THRESHOLD = 0.5
    TARGET_DICE_SWEEP_THRESHOLDS = tuple(round(x, 2) for x in np.arange(0.05, 1.00, 0.05))
    TARGET_DICE_TOP_PERCENT = 1.0
    # Internal operating point: fixed false-positive rate at 5%.
    # FPR = 1 - specificity, so this reports sensitivity/TPR at specificity 0.95.
    FIXED_SPECIFICITY_TARGET = 0.95
    FIXED_SENSITIVITY_TARGET = 0.90

    # ==========================================
    # 5. Training hyperparameters
    # ==========================================
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    SEED = 42

    NUM_EPOCHS = 100
    BATCH_SIZE = 4
    NUM_WORKERS = 2

    LR = 1e-4
    WEIGHT_DECAY = 1e-4
    LR_SCHEDULER = "CosineAnnealing"
    EARLY_STOP_PATIENCE = 200
    GRAD_CLIP_NORM = 12.0

    POS_WEIGHT_VAL = 2
    SYS_POS_WEIGHT_VAL = 1.0
    SYS_FOCAL_ALPHA = 0.75
    SYS_FOCAL_GAMMA = 2.0
    USE_SYS_CLASS_BALANCED_BCE = True

    # ==========================================
    # 6. Loss / EM weighting configuration
    # ==========================================
    EM_LR_MULTIPLIER = 10.0

    USE_LOGVAR_CLAMP = True
    LOGVAR_MIN = -2.0
    LOGVAR_MAX = 2.0

    # Auxiliary anatomical prior for TBx-only training. This does not create a
    # gland segmentation head; it only penalises lesion-risk logits outside the
    # available prostate gland mask.
    USE_OUTSIDE_GLAND_PENALTY = EXPERIMENT_MODE == "B1_TCIA_TBX_BASELINE"
    OUTSIDE_GLAND_LOSS_WEIGHT = 0.05 if USE_OUTSIDE_GLAND_PENALTY else 0.0
    OUTSIDE_GLAND_START_EPOCH = 1

    FIXED_LOSS_WEIGHTS = {
        "grade_tbx": 0.0,
        "grade_sbx": 0.0,
        "lesion_dense": LESION_DENSE_LOSS_WEIGHT,
        "lesion_sparse": LESION_SPARSE_LOSS_WEIGHT,
        "lesion_sys": LESION_SYS_LOSS_WEIGHT,
        "lesion_outside_gland": OUTSIDE_GLAND_LOSS_WEIGHT,
        "gland": 0.0,
    }

    TBX_POSITIVE_SOFT_LABEL = 0.9
    TBX_NEGATIVE_SOFT_LABEL = 0.05
    # If False, TBx ROI loss is hard-label BCE on sampled target ROIs:
    #   positive: target_mask >= LESION_POSITIVE_THRESHOLD
    #   negative: 0 < target_mask < LESION_POSITIVE_THRESHOLD
    # target_mask == 0 remains unsampled/no-supervision.
    USE_TBX_POSITIVE_ONLY_LOSS = False

    GRADE_TBX_START_EPOCH = 1
    GRADE_SBX_START_EPOCH = 1
    GLAND_START_EPOCH = 1

    LESION_W_SMALL = 5

    # ==========================================
    # 7. Ablation and augmentation
    # ==========================================
    USE_AUGMENTATION = True
    MASK_TARGET_IN_SYS = True

    # ==========================================
    # 8. Visualization
    # ==========================================
    VIS_SUBDIR = "visualizations"
    SAVE_TRAIN_VIS = True
    TRAIN_VIS_EVERY_N_EPOCHS = 5
    TRAIN_VIS_MAX_PER_EPOCH = 4
    SAVE_VAL_VIS = True
    VAL_VIS_EVERY_N_EPOCHS = 5
    VAL_VIS_MAX_PER_TYPE = 2

    @classmethod
    def set_seed(cls):
        random.seed(cls.SEED)
        np.random.seed(cls.SEED)
        torch.manual_seed(cls.SEED)
        if torch.cuda.is_available():
            torch.cuda.manual_seed(cls.SEED)
            torch.cuda.manual_seed_all(cls.SEED)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False

    @classmethod
    def show(cls):
        print("-" * 50)
        print("Experiment Configurations:")
        for k, v in cls.__dict__.items():
            if not k.startswith("__") and not callable(v) and not isinstance(v, classmethod):
                print(f"{k:<32}: {v}")
        print("-" * 50)

    @classmethod
    def enabled_task_name(cls):
        enabled = []
        if getattr(cls, "USE_LESION_DENSE_TASK", False):
            enabled.append("LesDense")
        if getattr(cls, "USE_LESION_SPARSE_TASK", False):
            enabled.append("LesTBxROI")
        if getattr(cls, "USE_LESION_SYS_TASK", False):
            enabled.append("LesSysSBx")
        return "_".join(enabled) if enabled else "NoTask"

    @classmethod
    def get_experiment_name(cls):
        time_str = datetime.now().strftime("%Y%m%d_%H%M")
        weighting_name = "EM" if getattr(cls, "USE_EM_WEIGHTING", True) else "FixedW"
        task_name = cls.enabled_task_name()
        clamp_name = "Clamp" if getattr(cls, "USE_LOGVAR_CLAMP", False) else "NoClamp"
        curriculum_name = "Curr" if getattr(cls, "USE_CURRICULUM", False) else "NoCurr"
        em_lr = getattr(cls, "EM_LR_MULTIPLIER", 1.0)
        tag = getattr(cls, "EXPERIMENT_TAG", "")

        parts = [time_str]
        if tag:
            parts.append(str(tag))
        parts.extend([
            weighting_name,
            task_name,
            clamp_name,
            curriculum_name,
            f"EMlrX{em_lr:g}",
            f"LR{cls.LR}",
            str(cls.BEST_MODEL_METRIC),
        ])
        name = "_".join(parts)
        if not getattr(cls, "USE_AUGMENTATION", True):
            name += "_NoAug"
        return name
