import os
import random
from datetime import datetime

import numpy as np
import torch


class Config:
    # ==========================================
    # 1. Path configurations
    # ==========================================
    # HPC default: keep experiments under the project checkout, while allowing
    # local runs to override the dataset mount with RP_DATASET_ROOT.
    BASE_DIR = r"/raid/candi/jiayi/RP"
    DATASET_ROOT = os.environ.get("RP_DATASET_ROOT", os.path.join(BASE_DIR, "data"))
    UNIFIED_DATA_DIR = os.path.join(DATASET_ROOT, "Unified_Dataset")
    SPLIT_DIR = os.path.join(UNIFIED_DATA_DIR, "splits")
    EXP_DIR = os.path.join(BASE_DIR, "Experiments")

    # ==========================================
    # 2. Experiment mode
    # ==========================================
    # Options:
    #   "B1_TCIA_TBX_BASELINE"
    #       Main baseline: TCIA TBx-confirmed radiologist target lesion ROIs only.
    #
    #   "B2_TCIA_SBX_ONLY"
    #       TCIA systematic-biopsy region supervision only.
    #
    #   "B3_TCIA_TBX_SBX"
    #       TCIA TBx-confirmed target ROIs + TCIA SBx region supervision.
    #
    #   Mixed-supervision source combinations:
    #       N1_RADIOLOGIST_ONLY   = RA only
    #       N2_PUB_TCIA_TBX_ONLY = RA + TBx
    #       N3_PUB_TCIA_SBX_ONLY = RA + SBx
    #       N4_MIXED              = RA + TBx + SBx
    #
    # Every experiment uses the same unmasked PUB + TCIA internal evaluation
    # cohorts and the same PROMIS external cohort. This allows all supervision
    # combinations to report metrics on identical patient sets:
    #   - lesion Dice on valid PUB dense-mask cases;
    #   - patient-level risk-map metrics from available segmentation masks;
    #   - region-level risk-map metrics from available masks and zone maps.
    #
    # Change only this value to switch experiments.
    EXPERIMENT_MODE = "B1_TCIA_TBX_BASELINE"

    # Shared evaluation cohorts generated by
    # preprocessing/Dataset_split_generator.py.
    COMMON_INTERNAL_VAL_CSV = os.path.join(
        SPLIT_DIR, "common_internal_evaluation.csv"
    )
    COMMON_INTERNAL_TEST_CSV = os.path.join(
        SPLIT_DIR, "common_internal_test.csv"
    )
    # This existing mixed-supervision split is the canonical PROMIS cohort.
    # All task wrappers point to this exact file rather than task-specific copies.
    COMMON_EXTERNAL_TEST_CSV = os.path.join(
        SPLIT_DIR, "N4_mixed_PROMIS_external_val.csv"
    )
    COMMON_FINAL_TEST_DATASETS = (
        ("internal", COMMON_INTERNAL_TEST_CSV),
        ("external", COMMON_EXTERNAL_TEST_CSV),
    )

    # AUPRC-based mixed-supervision checkpoint selection. Unlike the historical
    # composite metric, this rule does not depend on thresholded BACC.
    COMMON_BEST_MODEL_METRIC = "mixed_auprc"

    if EXPERIMENT_MODE == "B1_TCIA_TBX_BASELINE":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B1_TCIA_TBx_baseline_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "tbx_roi_auprc"
        EXPERIMENT_TAG = "B1_TCIA_TBxROI_PosNeg_OutsideGland_PatientRisk"

    elif EXPERIMENT_MODE == "B2_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B2_TCIA_SBx_only_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "region_auprc"
        EXPERIMENT_TAG = "B2_TCIA_SBxOnly"

    elif EXPERIMENT_MODE == "B3_TCIA_TBX_SBX":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B3_TCIA_TBx_SBx_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 10

        BEST_MODEL_METRIC = "biopsy_auprc_composite"
        EXPERIMENT_TAG = "B3_TCIA_TBxROI_SBx_PosNeg"

    elif EXPERIMENT_MODE == "N1_RADIOLOGIST_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N1_radiologist_only_train.csv"
        )
        # Train strictly on PUB cases with dense radiologist lesion masks.
        # Keep common validation unfiltered across supervised PUB/TCIA cases
        # so the run can still report comparison metrics.
        TASK = "mixed"
        DATASET_TASK = "mixed"
        TRAIN_DATASET_TASK = "radiologist_only"
        VAL_DATASET_TASK = "mixed"
        TEST_DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "lesion_dice"
        EXPERIMENT_TAG = "N1_PUBDenseOnly_CommonEval"

    elif EXPERIMENT_MODE == "N2_PUB_TCIA_TBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N2_PUB_TCIA_TBx_only_train.csv"
        )
        # The N2 training CSV contains PUB + TCIA TBx supervision.
        # TCIA SBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "ra_tbx_auprc_composite"
        EXPERIMENT_TAG = "N2_RA_TBx_FixedW1_1_NoCurr_OutsideGland_PatientRisk_CommonEval"

    elif EXPERIMENT_MODE == "N3_PUB_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N3_PUB_TCIA_SBx_only_train.csv"
        )
        # The N3 training CSV contains PUB + TCIA SBx supervision.
        # TCIA TBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        # Train dense RA and regional SBx supervision jointly from epoch 1.
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "ra_sbx_auprc_composite"
        EXPERIMENT_TAG = "N3_RA_SBx_FixedW1_1_NoCurr_OutsideGland_PatientRisk_CommonEval"

    elif EXPERIMENT_MODE == "N4_MIXED":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N4_mixed_PUB_TCIA_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.05
        LESION_SYS_LOSS_WEIGHT = 0.25

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        # Evidence-guided N4 default after N2/N3 sweeps:
        # Epoch 1-14:  PUB dense only
        # Epoch 15+:   PUB dense + TCIA TBx + TCIA SBx
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 15
        LESION_SYS_START_EPOCH = 15

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N4_FixedW005_025_Curr15_15_OutsideGland_PatientRisk_CommonEval"

    else:
        raise ValueError(
            "Unsupported EXPERIMENT_MODE: "
            f"{EXPERIMENT_MODE}. "
            "Use B1_TCIA_TBX_BASELINE, B2_TCIA_SBX_ONLY, "
            "B3_TCIA_TBX_SBX, or the N1/N2/N3/N4 supervision combinations."
        )

    # Universal evaluation protocol. Training supervision changes by experiment,
    # but validation and final-test patient sets never do.
    VAL_CSV = COMMON_INTERNAL_VAL_CSV
    INTERNAL_TEST_CSV = COMMON_INTERNAL_TEST_CSV
    TEST_CSV = COMMON_EXTERNAL_TEST_CSV
    FINAL_TEST_DATASETS = COMMON_FINAL_TEST_DATASETS

    # ==========================================
    # 3. Data and preprocessing
    # ==========================================
    TARGET_SPACING = [1.0, 1.0, 2.24]
    CROP_SIZE_SITK = [64, 64, 32]
    INPUT_SHAPE = (3, 32, 64, 64)
    # TCIA TBx supervision uses radiologist target lesion ROIs labelled by
    # target-biopsy-confirmed grade, not the inserted needle track.
    TCIA_TARGET_MASK_FILENAME = "target_mask.nii.gz"
    # Used only during preprocessing to match biopsy cores to target ROIs.
    NEEDLE_RADIUS = 2

    # ==========================================
    # 4. Model and labels
    # ==========================================
    IN_CHANNELS = 3
    NUM_CLASSES = 7

    # Compatibility values for the revised segmentation/MIL model.
    BASE_CHANNELS = 32
    MAX_ZONES = 20
    MIL_POOLING = "lme"
    LME_R = 8.0
    DROPOUT_RATE = 0.2
    # Patient evaluation mirrors the patient training loss: convert risk-map
    # probabilities back to logits, apply normalised log-mean-exp pooling, then
    # convert the pooled logit to a probability. Region evaluation keeps the
    # established top-percent pooling rule.
    SEG_PATIENT_POOLING = "logit_lme"
    SEG_REGION_POOLING = "top_percent"
    SEG_RISK_TOP_PERCENT = 1.0
    SEG_RISK_LME_R = 8.0
    # Deployment-oriented evaluation: if test-time gland masks are unavailable,
    # patient scores should be pooled from the same full crop at validation/test.
    SEG_EVAL_USE_GLAND_MASK = False

    # Label convention:
    # 0: negative/background, 1: benign, 2: ISUP1,
    # 3: ISUP2, ..., 6: ISUP5.
    CSPC_THRESHOLD = 3
    LESION_POSITIVE_THRESHOLD = CSPC_THRESHOLD
    INVALID_SYS_LABEL = -1
    PRED_PROB_THRESHOLD = 0.5
    TARGET_DICE_SWEEP_THRESHOLDS = tuple(round(x, 2) for x in np.arange(0.05, 1.00, 0.05))
    TARGET_DICE_TOP_PERCENT = 1.0
    FROC_SWEEP_THRESHOLDS = tuple(round(x, 2) for x in np.arange(0.05, 1.00, 0.05))
    FROC_FP_PER_PATIENT_TARGETS = (0.5, 1.0, 2.0)
    FROC_MIN_COMPONENT_VOXELS = 1
    # ROC classification operating points. These are sample-level FPR/specificity
    # values, not lesion-detection FP/patient; FROC uses the settings above.
    FIXED_SPECIFICITY_TARGET = 0.95
    FIXED_SENSITIVITY_TARGET = 0.90
    # Compute ROC fixed-specificity/sensitivity during validation, but keep the
    # heavier FROC connected-component sweep for final test only.
    VALIDATION_COMPUTE_OPERATING_METRICS = True
    VALIDATION_COMPUTE_FROC_METRICS = False
    FINAL_TEST_COMPUTE_OPERATING_METRICS = True
    FINAL_TEST_COMPUTE_FROC_METRICS = True
    # Save and test several epoch checkpoints, not only the validation-selected
    # best checkpoint. Missing epochs are ignored, e.g. after early stopping.
    FINAL_TEST_CHECKPOINT_EPOCHS = (25, 50, 75, 100, 125, 150)
    FINAL_TEST_INCLUDE_BEST = True
    FINAL_TEST_INCLUDE_LAST = True

    # ==========================================
    # 5. Training hyperparameters
    # ==========================================
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    SEED = 42

    NUM_EPOCHS = 150
    BATCH_SIZE = 4
    NUM_WORKERS = 2

    LR = 1e-4
    WEIGHT_DECAY = 1e-4
    LR_SCHEDULER = "CosineAnnealing"
    EARLY_STOP_PATIENCE = 200
    GRAD_CLIP_NORM = 12.0

    POS_WEIGHT_VAL = 2
    SYS_POS_WEIGHT_VAL = 1.0
    SYS_FOCAL_ALPHA = 0.75
    SYS_FOCAL_GAMMA = 2.0
    USE_SYS_CLASS_BALANCED_BCE = True

    # ==========================================
    # 6. Loss / EM weighting configuration
    # ==========================================
    EM_LR_MULTIPLIER = 10.0

    USE_LOGVAR_CLAMP = True
    LOGVAR_MIN = -2.0
    LOGVAR_MAX = 2.0

    # Anatomical consistency supervision on the shared lesion risk map. N2-N4
    # use the same term as B1 so the mixed-supervision models retain the same
    # outside-prostate false-positive constraint.
    USE_OUTSIDE_GLAND_PENALTY = EXPERIMENT_MODE in {
        "B1_TCIA_TBX_BASELINE",
        "N2_PUB_TCIA_TBX_ONLY",
        "N3_PUB_TCIA_SBX_ONLY",
        "N4_MIXED",
    }
    OUTSIDE_GLAND_LOSS_WEIGHT = 0.05 if USE_OUTSIDE_GLAND_PENALTY else 0.0
    OUTSIDE_GLAND_START_EPOCH = 1

    # Patient-level supervision derived from the same lesion risk map. No
    # independent classification head is added: patient logits are pooled from
    # voxel lesion logits.
    USE_PATIENT_RISK_LOSS = EXPERIMENT_MODE in {
        "B1_TCIA_TBX_BASELINE",
        "N2_PUB_TCIA_TBX_ONLY",
        "N3_PUB_TCIA_SBX_ONLY",
        "N4_MIXED",
    }
    PATIENT_RISK_LOSS_WEIGHT = 0.05 if USE_PATIENT_RISK_LOSS else 0.0
    PATIENT_RISK_START_EPOCH = 1
    PATIENT_RISK_POOLING = "lme"
    PATIENT_RISK_LME_R = 8.0
    PATIENT_RISK_USE_GLAND_MASK = False
    # A dense RA lesion mask denotes radiological lesion presence, not
    # biopsy-confirmed patient csPCa. Keep the legacy fallback off so P has one
    # consistent clinical meaning across training and evaluation.
    USE_RA_LESION_PRESENCE_AS_PATIENT_LABEL = False

    FIXED_LOSS_WEIGHTS = {
        "grade_tbx": 0.0,
        "grade_sbx": 0.0,
        "lesion_dense": LESION_DENSE_LOSS_WEIGHT,
        "lesion_sparse": LESION_SPARSE_LOSS_WEIGHT,
        "lesion_sys": LESION_SYS_LOSS_WEIGHT,
        "lesion_outside_gland": OUTSIDE_GLAND_LOSS_WEIGHT,
        "lesion_patient": PATIENT_RISK_LOSS_WEIGHT,
        "gland": 0.0,
    }

    TBX_POSITIVE_SOFT_LABEL = 0.9
    TBX_NEGATIVE_SOFT_LABEL = 0.05
    # If False, TBx ROI loss is hard-label BCE on sampled target ROIs:
    #   positive: target_mask >= LESION_POSITIVE_THRESHOLD
    #   negative: 0 < target_mask < LESION_POSITIVE_THRESHOLD
    # target_mask == 0 remains unsampled/no-supervision.
    USE_TBX_POSITIVE_ONLY_LOSS = False

    GRADE_TBX_START_EPOCH = 1
    GRADE_SBX_START_EPOCH = 1
    GLAND_START_EPOCH = 1

    LESION_W_SMALL = 5

    # ==========================================
    # 7. Ablation and augmentation
    # ==========================================
    USE_AUGMENTATION = True
    MASK_TARGET_IN_SYS = True

    # ==========================================
    # 8. Visualization
    # ==========================================
    VIS_SUBDIR = "visualizations"
    SAVE_TRAIN_VIS = True
    TRAIN_VIS_EVERY_N_EPOCHS = 5
    TRAIN_VIS_MAX_PER_EPOCH = 4
    SAVE_VAL_VIS = True
    VAL_VIS_EVERY_N_EPOCHS = 5
    VAL_VIS_MAX_PER_TYPE = 2
    # Final-test artifacts are stored separately for every dataset/checkpoint.
    # "representative" keeps errors plus the first positive/negative case per
    # source; use "all", "errors", or "none" when a different policy is needed.
    TEST_ARTIFACT_SUBDIR = "test_artifacts"
    TEST_VIS_POLICY = "representative"
    TEST_VIS_MAX_PER_RUN = 12
    TEST_VIS_LOW_DICE_THRESHOLD = 0.5

    @classmethod
    def set_seed(cls):
        random.seed(cls.SEED)
        np.random.seed(cls.SEED)
        torch.manual_seed(cls.SEED)
        if torch.cuda.is_available():
            torch.cuda.manual_seed(cls.SEED)
            torch.cuda.manual_seed_all(cls.SEED)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False

    @classmethod
    def show(cls):
        print("-" * 50)
        print("Experiment Configurations:")
        for k, v in cls.__dict__.items():
            if not k.startswith("__") and not callable(v) and not isinstance(v, classmethod):
                print(f"{k:<32}: {v}")
        print("-" * 50)

    @classmethod
    def enabled_task_name(cls):
        enabled = []
        if getattr(cls, "USE_LESION_DENSE_TASK", False):
            enabled.append("LesDense")
        if getattr(cls, "USE_LESION_SPARSE_TASK", False):
            enabled.append("LesTBxROI")
        if getattr(cls, "USE_LESION_SYS_TASK", False):
            enabled.append("LesSysSBx")
        return "_".join(enabled) if enabled else "NoTask"

    @classmethod
    def get_experiment_name(cls):
        time_str = datetime.now().strftime("%Y%m%d_%H%M")
        weighting_name = "EM" if getattr(cls, "USE_EM_WEIGHTING", True) else "FixedW"
        task_name = cls.enabled_task_name()
        clamp_name = "Clamp" if getattr(cls, "USE_LOGVAR_CLAMP", False) else "NoClamp"
        curriculum_name = "Curr" if getattr(cls, "USE_CURRICULUM", False) else "NoCurr"
        em_lr = getattr(cls, "EM_LR_MULTIPLIER", 1.0)
        tag = getattr(cls, "EXPERIMENT_TAG", "")

        parts = [time_str]
        if tag:
            parts.append(str(tag))
        parts.extend([
            weighting_name,
            task_name,
            clamp_name,
            curriculum_name,
            f"EMlrX{em_lr:g}",
            f"LR{cls.LR}",
            str(cls.BEST_MODEL_METRIC),
        ])
        name = "_".join(parts)
        if not getattr(cls, "USE_AUGMENTATION", True):
            name += "_NoAug"
        return name
