import os
import random
from datetime import datetime

import numpy as np
import torch


class Config:
    # ==========================================
    # 1. Path configurations
    # ==========================================
    BASE_DIR = r"/raid/candi/jiayi/RP"
    UNIFIED_DATA_DIR = os.path.join(BASE_DIR, "data", "Unified_Dataset")
    SPLIT_DIR = os.path.join(UNIFIED_DATA_DIR, "splits")
    EXP_DIR = os.path.join(BASE_DIR, "Experiments")

    # ==========================================
    # 2. Experiment mode
    # ==========================================
    # Options:
    #   "N1_RADIOLOGIST_ONLY"
    #       Train with PUB dense radiologist lesion masks only.
    #
    #   "N2_PUB_TCIA_TBX_ONLY"
    #       Train with PUB dense masks + TCIA TBx supervision only.
    #
    #   "N3_PUB_TCIA_SBX_ONLY"
    #       Train with PUB dense masks + TCIA SBx supervision only.
    #
    #   "N4_MIXED"
    #       Train with PUB dense masks + TCIA TBx + TCIA SBx.
    #
    # All N1-N4 experiments use the same unmasked PUB + TCIA internal
    # evaluation cohort. This allows every experiment to report:
    #   - lesion Dice on valid PUB dense-mask cases;
    #   - patient-level BACC on valid TCIA biopsy-labelled cases;
    #   - region-level BACC on valid TCIA SBx-labelled regions.
    #
    # Change only this value to switch experiments.
    EXPERIMENT_MODE = "N2_PUB_TCIA_TBX_ONLY"

    # Shared internal evaluation cohort generated by
    # Dataset_split_generator_common_eval.py.
    COMMON_INTERNAL_VAL_CSV = os.path.join(
        SPLIT_DIR, "common_internal_evaluation.csv"
    )

    # Use the same checkpoint-selection rule for fair N1-N4 comparison.
    # The evaluate/train code must calculate "composite" from the valid
    # lesion-, patient-, and region-level metrics using their label masks.
    COMMON_BEST_MODEL_METRIC = "composite"

    if EXPERIMENT_MODE == "N1_RADIOLOGIST_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N1_radiologist_only_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N1_PROMIS_external_val.csv"
        )

        # "mixed" prevents the common validation loader from filtering out
        # TCIA cases. The active loss switches below still ensure that N1 is
        # trained with PUB dense supervision only.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N1_RadiologistOnly_CommonEval"

    elif EXPERIMENT_MODE == "N2_PUB_TCIA_TBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N2_PUB_TCIA_TBx_only_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N2_PROMIS_external_val.csv"
        )

        # The N2 training CSV contains PUB + TCIA TBx supervision.
        # TCIA SBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N2_PUB_TCIA_TBxOnly_CommonEval"

    elif EXPERIMENT_MODE == "N3_PUB_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N3_PUB_TCIA_SBx_only_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N3_PROMIS_external_val.csv"
        )

        # The N3 training CSV contains PUB + TCIA SBx supervision.
        # TCIA TBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        USE_EM_WEIGHTING = True
        USE_CURRICULUM = True

        # Epoch 1-9: PUB dense only
        # Epoch 10+:  PUB dense + TCIA SBx
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 10

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N3_PUB_TCIA_SBxOnly_CommonEval"

    elif EXPERIMENT_MODE == "N4_MIXED":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N4_mixed_PUB_TCIA_train.csv"
        )
        VAL_CSV = COMMON_INTERNAL_VAL_CSV
        TEST_CSV = os.path.join(
            SPLIT_DIR, "N4_mixed_PROMIS_external_val.csv"
        )

        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        USE_EM_WEIGHTING = True
        USE_CURRICULUM = True

        # Epoch 1-9:   PUB dense only
        # Epoch 10-29: PUB dense + TCIA TBx
        # Epoch 30+:   PUB dense + TCIA TBx + TCIA SBx
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 10
        LESION_SYS_START_EPOCH = 30

        BEST_MODEL_METRIC = COMMON_BEST_MODEL_METRIC
        EXPERIMENT_TAG = "N4_Mixed_PUB_TCIA_CommonEval"

    else:
        raise ValueError(
            "Unsupported EXPERIMENT_MODE: "
            f"{EXPERIMENT_MODE}. "
            "Use N1_RADIOLOGIST_ONLY, N2_PUB_TCIA_TBX_ONLY, "
            "N3_PUB_TCIA_SBX_ONLY, or N4_MIXED."
        )

    # ==========================================
    # 3. Data and preprocessing
    # ==========================================
    TARGET_SPACING = [1.0, 1.0, 2.24]
    CROP_SIZE_SITK = [64, 64, 32]
    INPUT_SHAPE = (3, 32, 64, 64)
    NEEDLE_RADIUS = 2

    # ==========================================
    # 4. Model and labels
    # ==========================================
    IN_CHANNELS = 3
    NUM_CLASSES = 7

    # Compatibility values for the revised segmentation/MIL model.
    BASE_CHANNELS = 32
    MAX_ZONES = 20
    MIL_POOLING = "lme"
    LME_R = 8.0
    DROPOUT_RATE = 0.2

    # Label convention:
    # 0: negative/background, 1: benign, 2: ISUP1,
    # 3: ISUP2, ..., 6: ISUP5.
    CSPC_THRESHOLD = 3
    LESION_POSITIVE_THRESHOLD = CSPC_THRESHOLD
    INVALID_SYS_LABEL = -1
    PRED_PROB_THRESHOLD = 0.5

    # ==========================================
    # 5. Training hyperparameters
    # ==========================================
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    SEED = 42

    NUM_EPOCHS = 100
    BATCH_SIZE = 4
    NUM_WORKERS = 2

    LR = 1e-4
    WEIGHT_DECAY = 1e-4
    LR_SCHEDULER = "CosineAnnealing"
    EARLY_STOP_PATIENCE = 20
    GRAD_CLIP_NORM = 12.0

    POS_WEIGHT_VAL = 2

    # ==========================================
    # 6. Loss / EM weighting configuration
    # ==========================================
    EM_LR_MULTIPLIER = 10.0

    USE_LOGVAR_CLAMP = False
    LOGVAR_MIN = -3.0
    LOGVAR_MAX = 3.0

    FIXED_LOSS_WEIGHTS = {
        "grade_tbx": 0.0,
        "grade_sbx": 0.0,
        "lesion_dense": 1.0,
        "lesion_sparse": 0.25,
        "lesion_sys": 1.0,
        "gland": 0.0,
    }

    TBX_POSITIVE_SOFT_LABEL = 0.9
    TBX_NEGATIVE_SOFT_LABEL = 0.05

    GRADE_TBX_START_EPOCH = 1
    GRADE_SBX_START_EPOCH = 1
    GLAND_START_EPOCH = 1

    LESION_W_SMALL = 5

    # ==========================================
    # 7. Ablation and augmentation
    # ==========================================
    USE_AUGMENTATION = True
    MASK_TARGET_IN_SYS = True

    # ==========================================
    # 8. Visualization
    # ==========================================
    VIS_SUBDIR = "visualizations"

    @classmethod
    def set_seed(cls):
        random.seed(cls.SEED)
        np.random.seed(cls.SEED)
        torch.manual_seed(cls.SEED)
        if torch.cuda.is_available():
            torch.cuda.manual_seed(cls.SEED)
            torch.cuda.manual_seed_all(cls.SEED)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False

    @classmethod
    def show(cls):
        print("-" * 50)
        print("Experiment Configurations:")
        for k, v in cls.__dict__.items():
            if not k.startswith("__") and not callable(v) and not isinstance(v, classmethod):
                print(f"{k:<32}: {v}")
        print("-" * 50)

    @classmethod
    def enabled_task_name(cls):
        enabled = []
        if getattr(cls, "USE_LESION_DENSE_TASK", False):
            enabled.append("LesDense")
        if getattr(cls, "USE_LESION_SPARSE_TASK", False):
            enabled.append("LesSparseTBx")
        if getattr(cls, "USE_LESION_SYS_TASK", False):
            enabled.append("LesSysSBx")
        return "_".join(enabled) if enabled else "NoTask"

    @classmethod
    def get_experiment_name(cls):
        time_str = datetime.now().strftime("%Y%m%d_%H%M")
        weighting_name = "EM" if getattr(cls, "USE_EM_WEIGHTING", True) else "FixedW"
        task_name = cls.enabled_task_name()
        clamp_name = "Clamp" if getattr(cls, "USE_LOGVAR_CLAMP", False) else "NoClamp"
        curriculum_name = "Curr" if getattr(cls, "USE_CURRICULUM", False) else "NoCurr"
        em_lr = getattr(cls, "EM_LR_MULTIPLIER", 1.0)
        tag = getattr(cls, "EXPERIMENT_TAG", "")

        parts = [time_str]
        if tag:
            parts.append(str(tag))
        parts.extend([
            weighting_name,
            task_name,
            clamp_name,
            curriculum_name,
            f"EMlrX{em_lr:g}",
            f"LR{cls.LR}",
            str(cls.BEST_MODEL_METRIC),
        ])
        name = "_".join(parts)
        if not getattr(cls, "USE_AUGMENTATION", True):
            name += "_NoAug"
        return name
